# -*- coding: utf-8 -*-
"""fase3_fine_tuning_aula1_prepare-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Nym9UDkqYf3JPmowFBIGNU5O0MnBprD
"""

#Conexão com o Google Drive

from google.colab import drive
drive.mount('/content/drive')

import json

def process_line_complementary_dataset(item):
    #Processa cada linha do arquivo JSON Lines, que contém os campos 'story' e 'summary
    return {
        "input": f"SUMMARIZE THIS NEWS.\n[|News|] {item['story']}[|eNews|]\n\n[|summary|]{item['summary']}[|esummary|]"
    }

def process_news_summaries_file(file_path, processed_data):
    #Lê um arquivo JSON do nosso dataset, processa cada notícia para formatar conforme o solicitado e adiciona à lista processed_data
    with open(file_path, 'r', encoding='utf-8') as file:
        json_data = json.load(file)
        news_list = json_data["news_summaries"]

        for item in news_list:
            story = item["story"]
            summary = item["summary"]
            formatted_text = f"SUMMARIZE THIS NEWS.\n[|News|] {story}[|eNews|]\n\n[|summary|]{summary}[|esummary|]"
            processed_data.append({"input": formatted_text})

# Lista para armazenar todos os dados processados
processed_data = []

# Processar dados do arquivo JSON Lines do dataset complementar
with open(r'/content/drive/MyDrive/FIAP/fase3/fine-tuning/data.jsonl', 'r', encoding='utf-8') as file:
    for line in file:
        item = json.loads(line)
        processed_data.append(process_line_complementary_dataset(item))

# Adicionar dados processados do arquivo JSON regular à mesma lista
# process_news_summaries_file(r'news_summaries.json', processed_data)

# Salvar todos os dados processados em um arquivo JSON
output_filename = r'/content/drive/MyDrive/FIAP/fase3/fine-tuning/news_dataset_chat_data.json'
with open(output_filename, 'w', encoding='utf-8') as file:
    json.dump(processed_data, file, ensure_ascii=False, indent=4)

print(f"Todos os dados reformatados foram salvos em '{output_filename}'.")